// <auto-generated />
namespace MovieStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editCustomerTable2222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editCustomerTable2222));
        
        string IMigrationMetadata.Id
        {
            get { return "202005171735320_editCustomerTable2222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
